const TOKEN_KEY="kisan_saathi_token";
const LANGS={en:["English","en-IN"],hi:["हिन्दी","hi-IN"],te:["తెలుగు","te-IN"],ta:["தமிழ்","ta-IN"],kn:["ಕನ್ನಡ","kn-IN"],ml:["മലയാളം","ml-IN"],bn:["বাংলা","bn-IN"],mr:["मराठी","mr-IN"],gu:["ગુજરાતી","gu-IN"],pa:["ਪੰਜਾਬੀ","pa-IN"],or:["ଓଡ଼ିଆ","or-IN"],as:["অসমীয়া","as-IN"],ur:["اردو","ur-IN"],sa:["संस्कृतम्","sa-IN"],ne:["नेपाली","ne-IN"],sd:["سنڌي","sd-IN"],kok:["कोंकणी","kok-IN"],mai:["मैथिली","mai-IN"],doi:["डोगरी","doi-IN"],mni:["ꯃꯤꯇꯩ ꯂꯣꯟ","mni-IN"],sat:["ᱥᱟᱱᱛᱟᱲᱤ","sat-IN"],bho:["भोजपुरी","hi-IN"],raj:["राजस्थानी","hi-IN"]};
const tokenFromUrl=new URLSearchParams(location.search).get("token");
if(tokenFromUrl){localStorage.setItem(TOKEN_KEY,tokenFromUrl);history.replaceState({},document.title,"/");}
function authHeaders(){const t=localStorage.getItem(TOKEN_KEY);return t?{Authorization:"Bearer "+t}:{}}
async function loadSession(){const t=localStorage.getItem(TOKEN_KEY);if(!t)return false;try{const r=await fetch("/api/me",{headers:authHeaders()});if(!r.ok)throw 0;const u=await r.json();document.getElementById("authScreen").classList.add("hidden");document.getElementById("appShell").classList.remove("hidden");document.getElementById("userName").textContent=u.name||"Farmer";document.getElementById("userLocation").textContent=u.location||"Siddipet, Telangana";document.getElementById("avatar").textContent=(u.name||"KS").split(/\s+/).map(x=>x[0]).slice(0,2).join("").toUpperCase();window.currentUser=u;applyLanguage(u.language||"en");return true}catch(e){localStorage.removeItem(TOKEN_KEY);return false}}
async function authSubmit(url,body){const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Authentication failed");localStorage.setItem(TOKEN_KEY,d.token);await loadSession();go("dashboard")}
document.addEventListener("DOMContentLoaded",async()=>{document.getElementById("loginForm").onsubmit=async e=>{e.preventDefault();try{await authSubmit("/api/auth/login",{email:loginEmail.value,password:loginPassword.value})}catch(x){authError.textContent=x.message}};document.getElementById("registerForm").onsubmit=async e=>{e.preventDefault();try{await authSubmit("/api/auth/register",{name:regName.value,email:regEmail.value,password:regPassword.value})}catch(x){authError.textContent=x.message}};showRegister.onclick=()=>{loginForm.classList.add("hidden");showRegister.parentElement.classList.add("hidden");registerForm.classList.remove("hidden")};showLogin.onclick=()=>{registerForm.classList.add("hidden");loginForm.classList.remove("hidden");showRegister.parentElement.classList.remove("hidden")};document.getElementById("logoutBtn")?.addEventListener("click",()=>{localStorage.removeItem(TOKEN_KEY);location.reload()});const ok=await loadSession();if(ok)go("dashboard");\n});
const $=s=>document.querySelector(s), content=$("#content");
const pages=["dashboard","crop","soil","health","weather","markets","inputs","schemes","insurance","experts","learning","assistant","profile","settings"];
const nav=document.querySelectorAll(".nav");
function applyLanguage(lang){window.currentLanguage=lang;const sel=document.getElementById("languageSelect");if(sel)sel.value=lang;document.documentElement.lang=lang;} async function saveLanguage(lang){applyLanguage(lang);try{const r=await fetch("/api/me",{method:"PATCH",headers:{"Content-Type":"application/json",...authHeaders()},body:JSON.stringify({language:lang})});if(r.ok)window.currentUser=await r.json();}catch(e){} go(document.querySelector(".nav.active")?.dataset.page||"settings");} function speakText(text){if(!("speechSynthesis" in window)){toast("Voice playback is not supported on this device.");return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=(LANGS[window.currentLanguage||"en"]||LANGS.en)[1];u.rate=.9;speechSynthesis.speak(u);} function startVoiceInput(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast("Voice input is not supported on this browser.");return;}const r=new SR();r.lang=(LANGS[window.currentLanguage||"en"]||LANGS.en)[1];r.interimResults=false;r.onstart=()=>toast("Listening… speak your farming question");r.onresult=e=>{const q=document.getElementById("q");if(q){q.value=e.results[0][0].transcript;askAI();}};r.onerror=()=>toast("I could not hear that. Please try again.");r.start();} function go(p){nav.forEach(n=>n.classList.toggle("active",n.dataset.page===p));content.innerHTML=render(p)}
function card(title,body,extra=""){return `<section class="card"><h3>${title}</h3>${body}${extra}</section>`}
function render(p){
const common={dashboard:["Good evening, Ramesh 👋","Here is what is happening on your farm today."],crop:["Crop Planning","Choose crops suited to your land, season and farm conditions."],soil:["Soil Health","Track soil reports and understand what your crops need."],health:["Crop Health","Upload a crop photo to identify possible diseases and pests."],weather:["Weather & Alerts","Farming-oriented weather information for your location."],markets:["Mandi Markets","Compare local prices and spot market trends."],inputs:["Agricultural Inputs","Find seeds, fertilizers and approved farm inputs."],schemes:["Government Schemes","Discover agriculture schemes and eligibility information."],insurance:["Crop Insurance","Understand coverage, renewal and claim steps."],experts:["Ask an Expert","Connect your question with an agriculture specialist."],learning:["Learning Centre","Practical crop guides, tutorials and quizzes."],assistant:["AI Saathi","Ask questions using your farm context."],profile:["My Farm","Your farm, crops and personal agriculture profile."],settings:["Settings","Language, notifications, privacy and accessibility."]}[p];
let body="";
if(p==="dashboard")body=`<div class="hero"><div><span class="pill light">TODAY'S FARM BRIEF</span><h2>Warm & partly cloudy</h2><p>Good conditions for field inspection. Light rain is possible tomorrow.</p><button onclick="go('weather')">View forecast</button></div><div class="heroicon">🌤️</div></div><div class="grid four">${card("Farm area","<b class='big'>4.5</b> acres")} ${card("Active crops","<b class='big'>3</b>")} ${card("Soil health","<b class='big'>78%</b>")} ${card("Today's temp","<b class='big'>29°</b>")}</div><div class="grid three">${card("🌦️ Weather alert","<b>Rain expected tomorrow</b><p>Consider delaying irrigation.</p>",'<button onclick="go(\'weather\')">Open weather</button>')}${card("💧 Irrigation","<b>Tomorrow · 6:00 AM</b><p>Based on soil moisture + forecast.</p>")}${card("🐛 Crop health","<b>Check your cotton crop</b><p>Last scan was 6 days ago.</p>",'<button onclick="go(\'health\')">Scan crop</button>')}</div>${card("🌱 My crops",'<div class="rows"><div>Cotton <span>2.0 acres · Flowering</span></div><div>Maize <span>1.5 acres · Vegetative</span></div><div>Red gram <span>1.0 acre · Flowering</span></div></div>')}`;
if(p==="crop")body=card("India Crop Catalogue",'<p>Explore field crops, pulses, oilseeds, vegetables, fruits, spices and plantation crops with typical crop duration and selling guidance.</p><div class="grid two"><div><label>Crop search</label><input id="cropSearch" placeholder="e.g. tomato, mango, cotton"></div><div><label>Category</label><select id="cropType"><option value="">All crops</option><option>Vegetable</option><option>Fruit</option><option>Pulse</option><option>Oilseed</option><option>Cereal</option><option>Spice</option><option>Commercial crop</option><option>Plantation</option><option>Tree nut</option></select></div></div><button onclick="loadCropCatalog()">Find crops</button>')+card("Crop details & market planning",'<div id="cropCatalog"><p>Loading crop catalogue…</p></div>');if(p==="soil")body='<div class="grid three">'+card("Soil health score","<b class='big'>78%</b><div class='bar'><i style='width:78%'></i></div><p>Good overall condition. Potassium is slightly low.</p>")+card("Nutrients","<p>Nitrogen <b>71%</b></p><div class='bar'><i style='width:71%'></i></div><p>Phosphorus <b>83%</b></p><div class='bar'><i style='width:83%'></i></div><p>Potassium <b>52%</b></p><div class='bar'><i style='width:52%'></i></div>")+card("Add soil test",'<label>pH</label><input value="7.1"><label>Organic carbon</label><input value="0.62"><button onclick="toast(\'Soil test saved\')">Save report</button>')+'</div>';
if(p==="health")body=card("📷 Camera crop-health screening",'<p>Take a clear photo of the affected leaf, stem or fruit. On supported phones, the camera can open directly.</p><div class="grid two"><div><label>Crop (optional)</label><input id="scanCropName" placeholder="e.g. cotton, tomato, chilli"></div><div class="upload">📸<input type="file" accept="image/*" capture="environment" id="scanfile"><small>Camera or gallery</small></div></div><button onclick="scanCrop()">Analyze photo</button><div id="scanResult"></div>')+card("Safety first",'<p>Photo analysis is a screening aid, not a confirmed diagnosis. Do not apply farm chemicals or nutrients solely from a photo result. Follow product labels and local agricultural advice.</p>');
if(p==="weather")body=card("Today · Siddipet",'<div class="weather"><b class="big">29°C</b><span>🌤️ Partly cloudy</span></div><div class="forecast"><div>Mon<br>🌤️ 29°</div><div>Tue<br>🌧️ 27°</div><div>Wed<br>🌦️ 28°</div><div>Thu<br>☀️ 30°</div><div>Fri<br>☀️ 31°</div></div>')+card("Farm advisory","<b>Rain probability 65%</b><p>Avoid unnecessary irrigation tomorrow.</p>");
if(p==="markets")body=card("Crop-wise mandi & market planning",'<p>Choose any crop to see how to compare buyers, quality, transport, storage and net return. Current prices are not invented; verify the live commodity/market price before selling.</p><div class="grid two"><div><label>Crop</label><input id="marketCrop" placeholder="e.g. tomato, mango, cotton"></div><div><label>Quantity (optional)</label><input id="marketQty" type="number" placeholder="quintals"></div></div><button onclick="loadMarketGuidance()">Market guidance</button><div id="marketResult"></div>');
if(p==="inputs")body=card("🛒 Kisan Saathi Farm Store",'<p>Safer farm supplies with transparent unit pricing. Restricted crop-protection products are not sold through this demo; selection should be handled by an adult farmer with qualified/local agricultural guidance.</p><div class="grid two"><div><input id="inputSearch" placeholder="Search seeds, compost, soil kit…"></div><div><select id="inputCategory"><option value="">All categories</option><option>Seeds</option><option>Soil</option><option>Soil amendment</option><option>Bio input</option><option>Safety</option><option>Irrigation</option></select></div></div><button onclick="loadInputs()">Browse products</button><div id="inputList"></div>')+card("🧺 Your cart",'<div id="cartBox">Your cart is empty.</div><button onclick="placeInputOrder()">Place order</button>');
if(p==="schemes")body='<div class="grid two">'+card("PM-KISAN","Income support for eligible farmer families.",'<button onclick="toast(\'Scheme details opened\')">View details</button>')+card("Telangana Agriculture Services","Browse state farmer-support programs.",'<button onclick="toast(\'State scheme details opened\')">View details</button>')+'</div>';
if(p==="insurance")body='<div class="grid three">'+card("🛡️ Coverage","Learn about notified crops, risks and seasonal enrollment.")+card("📄 My policy","Not linked.",'<button onclick="toast(\'Policy linking started\')">Link policy</button>')+card("📞 Claim guidance","Keep policy details and crop-loss evidence ready.")+'</div>';
if(p==="experts")body='<div class="grid three">'+card("👨‍🌾 Crop specialist","Ask about disease, nutrients or cultivation.",'<button onclick="toast(\'Request sent\')">Request help</button>')+card("🧪 Soil expert","Discuss soil-test results.",'<button onclick="toast(\'Request sent\')">Request help</button>')+card("💧 Irrigation advisor","Discuss water scheduling.",'<button onclick="toast(\'Request sent\')">Request help</button>')+'</div>';
if(p==="learning")body='<div class="grid three">'+card("Cotton pest scouting","12 min · Practical field guide",'<button onclick="toast(\'Lesson opened\')">Start lesson</button>')+card("Soil test basics","8 min · Understand NPK and pH",'<button onclick="toast(\'Lesson opened\')">Start lesson</button>')+card("Irrigation challenge","Quiz · Weather-aware irrigation",'<button onclick="toast(\'Quiz started\')">Start quiz</button>')+'</div>';
if(p==="assistant")body=card("🤖 AI Saathi — Agriculture Copilot",'<div class="voice-tools"><button onclick="startVoiceInput()">🎙️ Speak</button><button onclick="speakLastAI()">🔊 Hear answer</button><button onclick="clearAIHistory()">🗑️ Clear chat</button></div><div id="messages" class="messages"><div class="msg bot">Namaste! Ask me about crops, soil, pests, weather or irrigation.</div></div><div class="chat"><input id="q" placeholder="Should I irrigate my cotton tomorrow?"><button onclick="askAI()">Send</button></div>');
if(p==="profile")body=card("👨‍🌾 Ramesh Kumar","<p>Farmer profile · Telangana</p><div class='grid three'><div><b>4.5 acres</b><small>Farm area</small></div><div><b>Black soil</b><small>Soil type</small></div><div><b>Borewell</b><small>Irrigation</small></div></div>")+card("Current crops",'<div class="rows"><div>🌿 Cotton <span>2.0 acres</span></div><div>🌽 Maize <span>1.5 acres</span></div><div>🫘 Red gram <span>1.0 acre</span></div></div>');
if(p==="settings")body='<div class="grid two">'+card("🌐 Language",'<select id="languageSelect" onchange="saveLanguage(this.value)"><option value="en">English</option><option value="hi">हिन्दी</option><option value="te">తెలుగు</option><option value="ta">தமிழ்</option><option value="kn">ಕನ್ನಡ</option><option value="ml">മലയാളം</option><option value="bn">বাংলা</option><option value="mr">मराठी</option><option value="gu">ગુજરાતી</option><option value="pa">ਪੰਜਾਬੀ</option><option value="or">ଓଡ଼ିଆ</option><option value="as">অসমীয়া</option><option value="ur">اردو</option><option value="sa">संस्कृतम्</option><option value="ne">नेपाली</option><option value="sd">سنڌي</option><option value="kok">कोंकणी</option><option value="mai">मैथिली</option><option value="doi">डोगरी</option><option value="mni">ꯃꯤꯇꯩ ꯂꯣꯟ</option><option value="sat">ᱥᱟᱱᱛᱟᱲᱤ</option><option value="bho">भोजपुरी</option><option value="raj">राजस्थानी</option></select><p>Your language is saved to your account. AI answers, voice input and voice playback follow this preference.</p>')+card("🔔 Alerts",'<label><input type="checkbox" checked> Weather alerts</label><label><input type="checkbox" checked> Crop-stage reminders</label>')+card("🔐 Privacy","Authenticated farmer data and deletion controls.")+card("📱 Accessibility","Mobile-first, low-bandwidth and voice-first workflows.")+'</div>';
return `<div class="page"><div class="eyebrow">KISAN SAATHI</div><h1>${common[0]}</h1><p class="subtitle">${common[1]}</p>${body}</div>`}
async function loadCropCatalog(){
  const box=$("#cropCatalog"); if(!box)return;
  box.innerHTML="<p>Loading…</p>";
  try{const q=encodeURIComponent($("#cropSearch")?.value.trim()||"");const type=encodeURIComponent($("#cropType")?.value||"");const r=await fetch("/api/crop-catalog?q="+q+"&type="+type);const rows=await r.json();
    box.innerHTML=rows.length?'<div class="rows">'+rows.map(x=>'<div><b>'+x.name+'</b> <span>'+x.category+' · '+x.duration+'</span><p>'+x.marketGuidance+'</p><button onclick="showCropMarket('+JSON.stringify(x.name)+')">Market plan</button></div>').join("")+'</div>':"<p>No crop matched your search.</p>";
  }catch(e){box.innerHTML="<p>Crop catalogue is temporarily unavailable.</p>";}
}
async function showCropMarket(crop){go("markets");setTimeout(()=>{const el=$("#marketCrop");if(el){el.value=crop;loadMarketGuidance();}},0)}
async function loadMarketGuidance(){
  const crop=$("#marketCrop")?.value.trim();const box=$("#marketResult");if(!crop||!box)return;
  box.innerHTML="<p>Loading market guidance…</p>";
  try{const r=await fetch("/api/market-guidance?crop="+encodeURIComponent(crop));const d=await r.json();if(!r.ok)throw new Error(d.error||"Crop not found");
    box.innerHTML=card("Selling plan — "+d.crop,'<p><b>Typical duration:</b> '+d.duration+'</p><p>'+d.guidance+'</p><h4>Farmer net-return check</h4><p>'+d.farmerProfit+'</p><h4>Buyer fairness</h4><p>'+d.buyerBenefit+'</p><p class="muted">'+d.livePriceSource+'</p>');
  }catch(e){box.innerHTML="<p>"+(e.message||"Could not load market guidance.")+"</p>";}
}
function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
async function loadAIHistory(){const m=$("#messages");if(!m)return;try{const r=await fetch("/api/ai/history",{headers:authHeaders()});if(!r.ok)return;const rows=await r.json();if(!rows.length)return;m.innerHTML=rows.map(x=>`<div class="msg ${x.role==="user"?"user":"bot"}">${x.content.replace(/[&<>]/g,"")}${x.role==="assistant"?`<button class="speak-answer" onclick='speakText(${JSON.stringify(x.content)})'>🔊 Hear</button>`:""}</div>`).join("");}catch(e){}}\nasync function askAI(){const q=$("#q");if(!q?.value.trim())return;const text=q.value.trim(),m=$("#messages");m.innerHTML+=`<div class="msg user">${text.replace(/[&<>]/g,"")}</div>`;q.value="";const pending=document.createElement("div");pending.className="msg bot";pending.textContent="Thinking…";m.appendChild(pending);try{const r=await fetch("/api/ai/ask",{method:"POST",headers:{"Content-Type":"application/json",...authHeaders()},body:JSON.stringify({question:text,language:window.currentLanguage||"en"})});const d=await r.json();pending.remove();if(!r.ok)throw new Error(d.error||"AI service unavailable");m.innerHTML+=`<div class="msg bot">${d.answer.replace(/[&<>]/g,"")}<button class="speak-answer" onclick='speakText(${JSON.stringify(d.answer)})'>🔊 Hear</button></div>`;m.scrollTop=m.scrollHeight}catch(e){pending.textContent=e.message||"AI assistant is temporarily unavailable."}}\nasync function clearAIHistory(){if(!confirm("Clear your AI chat history?"))return;await fetch("/api/ai/history",{method:"DELETE",headers:authHeaders()});go("assistant")}\nfunction speakLastAI(){const a=[...document.querySelectorAll(".msg.bot")].pop();if(a)speakText(a.innerText.replace("🔊 Hear",""));}\nfunction escapeHtml(s){return String(s).replace(/[&<>]/g,"");}
async function scanCrop(){const file=$("#scanfile")?.files?.[0],box=$("#scanResult");if(!file||!box){toast("Please choose or take a crop photo first.");return;}box.innerHTML="<div class=\"card\"><p>Analyzing photo…</p></div>";const fd=new FormData();fd.append("image",file);fd.append("crop",$("#scanCropName")?.value.trim()||"");try{const r=await fetch("/api/crop-health/scan",{method:"POST",headers:authHeaders(),body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||"Scan failed");box.innerHTML="<div class=\"scan-result\"><h3>Possible finding: "+escapeHtml(d.result)+"</h3><p><b>Confidence:</b> "+Math.round(d.confidence*100)+"%</p><div class=\"bar\"><i style=\"width:"+Math.round(d.confidence*100)+"%\"></i></div><p><b>Why:</b> "+escapeHtml(d.why||"Photo screening only.")+"</p><h4>What to do now</h4><p>"+escapeHtml(d.treatment||"Ask a local agriculture expert before treatment.")+"</p><h4>Nutrition</h4><p>"+escapeHtml(d.fertilizer||"Use soil-test and crop-stage guidance.")+"</p><h4>Precautions</h4><p>"+escapeHtml(d.precaution||"Follow product labels and local agricultural advice.")+"</p><div id=\"scanProducts\" class=\"recommended-products\"><p>Finding suitable store inputs…</p></div></div>";loadHealthRecommendations(d.result,$("#scanCropName")?.value.trim()||"");}catch(e){box.innerHTML="<p>"+escapeHtml(e.message||"Photo analysis unavailable.")+"</p>";}}
function loadHealthRecommendations(result,crop){const box=$("#scanProducts");if(!box)return;fetch("/api/crop-health/recommendations?crop="+encodeURIComponent(crop)+"&result="+encodeURIComponent(result)).then(r=>r.json()).then(d=>{box.innerHTML="<h4>Suggested Kisan Saathi store inputs</h4><p class=\"muted\">"+escapeHtml(d.notice)+"</p>"+(d.recommendations||[]).map(p=>"<div class=\"product-row recommended\"><div><b>"+escapeHtml(p.name)+"</b><span>"+escapeHtml(p.category)+" · "+escapeHtml(p.unit)+"</span><p>"+escapeHtml(p.reason)+"</p></div><strong>₹"+Number(p.price).toLocaleString("en-IN")+"</strong><button onclick=\"buyRecommended("+JSON.stringify(p.id)+")\">Buy</button></div>").join("");}).catch(()=>{box.innerHTML="<p>Store recommendations are temporarily unavailable.</p>";});}
function buyRecommended(id){addToCart(id);go("inputs");setTimeout(()=>{loadInputs();renderCart();},0);}
async function loadInputs(){const box=$("#inputList");if(!box)return;box.innerHTML="<p>Loading products…</p>";try{const q=encodeURIComponent($("#inputSearch")?.value.trim()||""),cat=encodeURIComponent($("#inputCategory")?.value||"");const r=await fetch("/api/inputs?q="+q+"&category="+cat);const rows=await r.json();box.innerHTML=rows.map(p=>"<div class=\"product-row\"><div><b>"+escapeHtml(p.name)+"</b><span>"+escapeHtml(p.category)+" · "+escapeHtml(p.unit)+"</span><p>"+escapeHtml(p.description)+"</p></div><strong>₹"+Number(p.price).toLocaleString("en-IN")+"</strong><button onclick=\"addToCart("+JSON.stringify(p.id)+")\">Add</button></div>").join("")||"<p>No products matched.</p>";}catch(e){box.innerHTML="<p>Store unavailable.</p>";}}
function getCart(){try{return JSON.parse(localStorage.getItem("ks_cart")||"[]")}catch{return[]}}
async function renderCart(){const box=$("#cartBox");if(!box)return;const c=getCart();if(!c.length){box.innerHTML="Your cart is empty.";return;}try{const r=await fetch("/api/inputs");const products=await r.json();let total=0;box.innerHTML=c.map(i=>{const p=products.find(x=>x.id===i.id);if(!p)return"";total+=p.price*i.qty;return "<div class=\"cart-row\"><span>"+escapeHtml(p.name)+" × "+i.qty+"</span><b>₹"+(p.price*i.qty).toLocaleString("en-IN")+"</b><button onclick=\"removeFromCart("+JSON.stringify(i.id)+")\">Remove</button></div>"}).join("")+"<hr><b>Total: ₹"+total.toLocaleString("en-IN")+"</b>";}catch{}}
function saveCart(c){localStorage.setItem("ks_cart",JSON.stringify(c));renderCart()}
function addToCart(id){const c=getCart(),x=c.find(i=>i.id===id);if(x)x.qty++;else c.push({id,qty:1});saveCart(c);toast("Added to cart")}
function removeFromCart(id){saveCart(getCart().filter(x=>x.id!==id))}
async function placeInputOrder(){const c=getCart();if(!c.length){toast("Your cart is empty");return;}const note=prompt("Delivery note (optional):","Please call before delivery");try{const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json",...authHeaders()},body:JSON.stringify({items:c,delivery_note:note||""})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Order failed");localStorage.removeItem("ks_cart");renderCart();toast("Order #"+d.orderId+" placed");}catch(e){toast(e.message||"Could not place order")}}
nav.forEach(n=>n.addEventListener("click",()=>go(n.dataset.page)));
$("#menu").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");
$("#voiceBtn").onclick=()=>startVoiceInput();
$("#bell").onclick=()=>toast("3 farming alerts: rain, irrigation and cotton scouting");
go("dashboard");