const $=s=>document.querySelector(s), content=$("#content");
const pages=["dashboard","crop","soil","health","weather","markets","inputs","schemes","insurance","experts","learning","assistant","profile","settings"];
const nav=document.querySelectorAll(".nav");
function go(p){nav.forEach(n=>n.classList.toggle("active",n.dataset.page===p));content.innerHTML=render(p)}
function card(title,body,extra=""){return `<section class="card"><h3>${title}</h3>${body}${extra}</section>`}
function render(p){
const common={dashboard:["Good evening, Ramesh 👋","Here is what is happening on your farm today."],crop:["Crop Planning","Choose crops suited to your land, season and farm conditions."],soil:["Soil Health","Track soil reports and understand what your crops need."],health:["Crop Health","Upload a crop photo to identify possible diseases and pests."],weather:["Weather & Alerts","Farming-oriented weather information for your location."],markets:["Mandi Markets","Compare local prices and spot market trends."],inputs:["Agricultural Inputs","Find seeds, fertilizers and approved farm inputs."],schemes:["Government Schemes","Discover agriculture schemes and eligibility information."],insurance:["Crop Insurance","Understand coverage, renewal and claim steps."],experts:["Ask an Expert","Connect your question with an agriculture specialist."],learning:["Learning Centre","Practical crop guides, tutorials and quizzes."],assistant:["AI Saathi","Ask questions using your farm context."],profile:["My Farm","Your farm, crops and personal agriculture profile."],settings:["Settings","Language, notifications, privacy and accessibility."]}[p];
let body="";
if(p==="dashboard")body=`<div class="hero"><div><span class="pill light">TODAY'S FARM BRIEF</span><h2>Warm & partly cloudy</h2><p>Good conditions for field inspection. Light rain is possible tomorrow.</p><button onclick="go('weather')">View forecast</button></div><div class="heroicon">🌤️</div></div><div class="grid four">${card("Farm area","<b class='big'>4.5</b> acres")} ${card("Active crops","<b class='big'>3</b>")} ${card("Soil health","<b class='big'>78%</b>")} ${card("Today's temp","<b class='big'>29°</b>")}</div><div class="grid three">${card("🌦️ Weather alert","<b>Rain expected tomorrow</b><p>Consider delaying irrigation.</p>",'<button onclick="go(\'weather\')">Open weather</button>')}${card("💧 Irrigation","<b>Tomorrow · 6:00 AM</b><p>Based on soil moisture + forecast.</p>")}${card("🐛 Crop health","<b>Check your cotton crop</b><p>Last scan was 6 days ago.</p>",'<button onclick="go(\'health\')">Scan crop</button>')}</div>${card("🌱 My crops",'<div class="rows"><div>Cotton <span>2.0 acres · Flowering</span></div><div>Maize <span>1.5 acres · Vegetative</span></div><div>Red gram <span>1.0 acre · Flowering</span></div></div>')}`;
if(p==="crop")body=card("Find suitable crops",'<label>Season</label><select><option>Kharif</option><option>Rabi</option></select><label>Soil</label><select><option>Black soil</option><option>Red soil</option></select><label>Water</label><select><option>Moderate</option><option>High</option><option>Low</option></select><button onclick="toast(\'Recommendations updated\')">Get recommendations</button>')+card("Recommended crops",'<div class="rows"><div>🌾 Cotton <span>150–180 days</span></div><div>🌽 Maize <span>90–120 days</span></div><div>🫘 Red gram <span>160–200 days</span></div></div>');
if(p==="soil")body='<div class="grid three">'+card("Soil health score","<b class='big'>78%</b><div class='bar'><i style='width:78%'></i></div><p>Good overall condition. Potassium is slightly low.</p>")+card("Nutrients","<p>Nitrogen <b>71%</b></p><div class='bar'><i style='width:71%'></i></div><p>Phosphorus <b>83%</b></p><div class='bar'><i style='width:83%'></i></div><p>Potassium <b>52%</b></p><div class='bar'><i style='width:52%'></i></div>")+card("Add soil test",'<label>pH</label><input value="7.1"><label>Organic carbon</label><input value="0.62"><button onclick="toast(\'Soil test saved\')">Save report</button>')+'</div>';
if(p==="health")body=card("📷 Upload crop photo",'<div class="upload">📸<p>Take a clear photo of the affected leaf, stem or fruit.</p><input type="file" accept="image/*" id="scanfile"><button onclick="scanCrop()">Analyze photo</button></div>')+card("Latest scan",'<b>Possible cotton leaf spot</b><p>Confidence: 86%</p><div class="bar"><i style="width:86%"></i></div><p>Confirm with a local agriculture expert before treatment.</p>');
if(p==="weather")body=card("Today · Siddipet",'<div class="weather"><b class="big">29°C</b><span>🌤️ Partly cloudy</span></div><div class="forecast"><div>Mon<br>🌤️ 29°</div><div>Tue<br>🌧️ 27°</div><div>Wed<br>🌦️ 28°</div><div>Thu<br>☀️ 30°</div><div>Fri<br>☀️ 31°</div></div>')+card("Farm advisory","<b>Rain probability 65%</b><p>Avoid unnecessary irrigation tomorrow.</p>");
if(p==="markets")body=card("Mandi prices",'<div class="rows"><div>Cotton · Siddipet <span>₹7,250/q ↑</span></div><div>Maize · Siddipet <span>₹2,180/q</span></div><div>Red gram · Sangareddy <span>₹7,950/q ↑</span></div></div>');
if(p==="inputs")body='<div class="grid three">'+card("🌱 Cotton Seed","₹780",'<button onclick="toast(\'Added to cart\')">Add</button>')+card("🧪 NPK Fertilizer","₹1,250",'<button onclick="toast(\'Added to cart\')">Add</button>')+card("🌿 Neem Bio Input","₹320",'<button onclick="toast(\'Added to cart\')">Add</button>')+'</div>';
if(p==="schemes")body='<div class="grid two">'+card("PM-KISAN","Income support for eligible farmer families.",'<button onclick="toast(\'Scheme details opened\')">View details</button>')+card("Telangana Agriculture Services","Browse state farmer-support programs.",'<button onclick="toast(\'State scheme details opened\')">View details</button>')+'</div>';
if(p==="insurance")body='<div class="grid three">'+card("🛡️ Coverage","Learn about notified crops, risks and seasonal enrollment.")+card("📄 My policy","Not linked.",'<button onclick="toast(\'Policy linking started\')">Link policy</button>')+card("📞 Claim guidance","Keep policy details and crop-loss evidence ready.")+'</div>';
if(p==="experts")body='<div class="grid three">'+card("👨‍🌾 Crop specialist","Ask about disease, nutrients or cultivation.",'<button onclick="toast(\'Request sent\')">Request help</button>')+card("🧪 Soil expert","Discuss soil-test results.",'<button onclick="toast(\'Request sent\')">Request help</button>')+card("💧 Irrigation advisor","Discuss water scheduling.",'<button onclick="toast(\'Request sent\')">Request help</button>')+'</div>';
if(p==="learning")body='<div class="grid three">'+card("Cotton pest scouting","12 min · Practical field guide",'<button onclick="toast(\'Lesson opened\')">Start lesson</button>')+card("Soil test basics","8 min · Understand NPK and pH",'<button onclick="toast(\'Lesson opened\')">Start lesson</button>')+card("Irrigation challenge","Quiz · Weather-aware irrigation",'<button onclick="toast(\'Quiz started\')">Start quiz</button>')+'</div>';
if(p==="assistant")body=card("🤖 AI Saathi",'<div id="messages" class="messages"><div class="msg bot">Namaste! Ask me about crops, soil, pests, weather or irrigation.</div></div><div class="chat"><input id="q" placeholder="Should I irrigate my cotton tomorrow?"><button onclick="askAI()">Send</button></div>');
if(p==="profile")body=card("👨‍🌾 Ramesh Kumar","<p>Farmer profile · Telangana</p><div class='grid three'><div><b>4.5 acres</b><small>Farm area</small></div><div><b>Black soil</b><small>Soil type</small></div><div><b>Borewell</b><small>Irrigation</small></div></div>")+card("Current crops",'<div class="rows"><div>🌿 Cotton <span>2.0 acres</span></div><div>🌽 Maize <span>1.5 acres</span></div><div>🫘 Red gram <span>1.0 acre</span></div></div>');
if(p==="settings")body='<div class="grid two">'+card("🌐 Language",'<select><option>English</option><option>తెలుగు</option><option>हिन्दी</option></select><p>Indian-language text and voice can be added as providers are connected.</p>')+card("🔔 Alerts",'<label><input type="checkbox" checked> Weather alerts</label><label><input type="checkbox" checked> Crop-stage reminders</label>')+card("🔐 Privacy","Authenticated farmer data and deletion controls.")+card("📱 Accessibility","Mobile-first, low-bandwidth and voice-first workflows.")+'</div>';
return `<div class="page"><div class="eyebrow">KISAN SAATHI</div><h1>${common[0]}</h1><p class="subtitle">${common[1]}</p>${body}</div>`}
function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
async function askAI(){const q=$("#q");if(!q?.value.trim())return;const m=$("#messages");m.innerHTML+=`<div class="msg user">${q.value}</div>`;try{const r=await fetch("/api/ai/ask",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q.value})});const d=await r.json();m.innerHTML+=`<div class="msg bot">${d.answer}</div>`}catch(e){m.innerHTML+=`<div class="msg bot">Please check your connection and try again.</div>`}q.value=""}
function scanCrop(){toast("Crop scan received. Demonstration result: possible leaf spot, 86% confidence.")}
nav.forEach(n=>n.addEventListener("click",()=>go(n.dataset.page)));
$("#menu").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");
$("#voiceBtn").onclick=()=>toast("Voice assistant ready");
$("#bell").onclick=()=>toast("3 farming alerts: rain, irrigation and cotton scouting");
go("dashboard");